const { Colors } = require("react-native/Libraries/NewAppScreen");

module.exports = {
  main_screen: {
    marginTop: 40,
    display: "flex",
    alignItems: "center",
    flexDirection: "column",
    backgroundColor: "white",
    width: "100%",
    height: "100%",
  },
  main_screen_display: {
    elevation: 10,
    width: "90%",
    backgroundColor: "white",
    borderRadius: 10,
    display: "flex",
    marginBottom: 10,
    padding: 10,
  },
  main_screen_display_text: {
    fontSize: 50,
    textAlign: "right",
  },
  main_screen_keypad: {
    width: "100%",
    height: "70%",
    display: "flex",
  },
  main_screen_keypad_row: {
    display: "flex",
    flexDirection: "row",
    backgroundColor: "white",
    justifyContent: "space-between",
    width: "100%",
    alignItems: "center",
    padding: 10,
  },
  btn_outer: {
    backgroundColor: "white",
    width: 70,
    height: 70,
    elevation: 10,
    borderRadius: 10,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  bg_button: {
    backgroundColor: "white",
    color: "black",
    fontSize: 30,
  },
  btn1_outer: {
    backgroundColor: "#FFAA33",
    width: 70,
    height: 70,
    elevation: 10,
    borderRadius: 90,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  bg1_button: {
    backgroundColor: "#FFAA33",
    fontWeight: "bold",
    color: "white",
    fontSize: 30,
  },
  btn2_outer: {
    backgroundColor: "lightgrey",
    width: 70,
    height: 70,
    elevation: 10,
    borderRadius: 90,
    overflow: "hidden",
    alignItems: "center",
    justifyContent: "center",
  },
  bg2_button: {
    backgroundColor: "lightgrey",
    fontWeight: "bold",
    color: "white",
    fontSize: 30,
  },
};
